spring:
  application:
    name: Student
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: lasan127
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
